name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: packages/react-native-gtk4
          tags: test
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: docker run -v "$(pwd)/coverage:/coverage" --rm test -- --coverage --coverageDirectory=/coverage
      - run: sudo chown -R $(id -u):$(id -g) ./coverage
      - uses: codecov/codecov-action@v4
        with:
          directory: ./coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: NODE_ENV=production pnpm run build
      - run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
