name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: sudo apt-get install -y libgtk-4-dev libgirepository1.0-dev build-essential
      - run: ./bin/setup
      - run: pnpm test -- -- --coverage --coverageDirectory=coverage
      - uses: codecov/codecov-action@v5
        with:
          directory: ./packages/react-native-gtk4/coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
